/** @format */
import swaggerAutogen from "swagger-autogen";
import path from "path"
import { PORT } from "./index.js";

const swaggerGen = () => {
	const doc = {
		info: {
			version: "3.0.0",
			title: "My API",
			description: "Documentation automatically generated by the <b>swagger-autogen</b> module.",
		},
		host: `localhost:${PORT}`,
		basePath: "/",
		schemes: ["http", "https"],
		consumes: ["application/json"],
		produces: ["application/json"],
		tags: [
			{
				name: "Users",
				description: "Endpoints",
			},
		],
		components: {}
	};

	const outputFile = "./src/Swagger/swagger-output.json";
	const endpointsFiles = [path.join(__dirname, "../../app.js")];

	swaggerAutogen(outputFile, endpointsFiles, doc).then(async () => {
		await require(path.join(__dirname, "../../app.js"));
	});
};

export default swaggerGen;